{% set name = "color-operations" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e072635a3a6709d83a05fa43804d4046f22aef44edd9afbc965eb1f435121697

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - color_operations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vincentsarago/color-operations
  summary: Apply basic color-oriented image operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - jsignell
