{% set name = "color-operations" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2090d367102301fb01d0edf9558be95c3998bb4cb14bb56228288feaa968d8af

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python

test:
  imports:
    - color_operations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vincentsarago/color-operations
  summary: Apply basic color-oriented image operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - jsignell
